### ISSUE TITLE
Numbers 15 Feb 2020

### ISSUE THREAD

**Issue by cspenn** [HopkinsIDD/nCoV-Sandbox#1]
Latest numbers from WHO and the JHU CSSE table:

[WHOSitrepTable2_20200211.csv.zip](https://github.com/HopkinsIDD/nCoV-Sandbox/files/4209220/WHOSitrepTable2_20200211.csv.zip)

**Comment by jlessler** [comment]
Thanks. Updated to incorporate this data.
